name: .NET CI and Release

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to release (engine | efcore)'
        required: true
        type: choice
        options:
          - engine
          - efcore
        default: engine
      version:
        description: 'SemVer version for the package (e.g., 1.0.0)'
        required: true
        type: string
      release_notes:
        description: 'Optional release notes for GitHub release'
        required: false
        type: string

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

  pack_and_publish:
    name: Pack and Publish to NuGet
    if: github.event_name == 'workflow_dispatch'
    needs: build_and_test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Pack Selected Package
        env:
          VERSION: ${{ github.event.inputs.version }}
          PACKAGE: ${{ github.event.inputs.package }}
        run: |
          echo "Requested package: $PACKAGE version: $VERSION"
          if [ "$PACKAGE" = "engine" ]; then
            echo "Packing ProtonFlow.BpmnEngine"
            dotnet pack ProtonFlow.BpmnEngine/ProtonFlow.BpmnEngine.csproj -c Release -o out \
              /p:PackageVersion=$VERSION \
              /p:ContinuousIntegrationBuild=true
          elif [ "$PACKAGE" = "efcore" ]; then
            echo "Packing ProtonFlow.Persistence.EfCore"
            dotnet pack ProtonFlow.Persistence.EfCore/ProtonFlow.Persistence.EfCore.csproj -c Release -o out \
              /p:PackageVersion=$VERSION \
              /p:ContinuousIntegrationBuild=true
          else
            echo "Unknown package $PACKAGE" && exit 1
          fi
          ls -1 out

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_PETERWIDMER }}
        run: |
          if [ -z "$NUGET_API_KEY" ]; then
            echo "Missing NUGET_API_KEY secret" && exit 1
          fi
          dotnet nuget push "out/*.nupkg" \
            --api-key "$NUGET_API_KEY" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate

      - name: Create GitHub Release (optional)
        if: ${{ github.event.inputs.release_notes != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}-${{ github.event.inputs.package }}
          name: ProtonFlow ${{ github.event.inputs.package }} v${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_notes }}
